version: '2.3'
services:
  ffmpeg:
    image: ffmpeg-nvidia
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /media:/media
      - $PWD:/data
    command: bash
    stdin_open: true
    tty: true
